In [88]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans

In [89]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [90]:
iris_dataset = load_iris()

In [91]:
data = iris_dataset.data
target_names = iris_dataset.target_names

target = iris_dataset.target
feature_names = iris_dataset.feature_names

In [92]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [93]:
X = pd.DataFrame(data, columns=feature_names)

In [94]:
y = pd.DataFrame(target)

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, target, random_state=42, train_size=0.8)

In [96]:
k_means = KMeans(n_init='auto', n_clusters=3, random_state=42)

In [97]:
k_means_model = k_means.fit(X_train)

In [98]:
predictions = k_means_model.predict(X_train)

In [99]:
k_means_model.cluster_centers_

array([[5.64333333, 2.67666667, 4.06      , 1.26      ],
       [4.99      , 3.4525    , 1.45      , 0.245     ],
       [6.564     , 2.98      , 5.348     , 1.888     ]])

In [100]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]

In [101]:
predictions

array([1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 0, 2, 1, 1, 0, 2, 2, 2, 2, 0, 2,
       0, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 1, 0, 1, 0, 2, 1, 0, 2, 1, 2, 2,
       0, 0, 2, 0, 1, 0, 2, 1, 1, 0, 2, 1, 2, 1, 1, 2, 0, 2, 2, 2, 2, 0,
       1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2,
       0, 0, 0, 1, 2, 0, 1, 0, 2, 2, 1, 0, 2, 2, 1, 2, 1, 2, 2, 2, 0, 2,
       0, 0, 2, 2, 1, 0, 0, 1, 0, 2], dtype=int32)

In [102]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [103]:
accuracy_score(y_train, predictions)

0.31666666666666665